In [1]:
import pandas as pd
import boto3
from io import StringIO

s3 = boto3.client('s3')

bucket_name = 'aws-nyc311-krame154-2026'
file_name = 'modeling/modeling_data.csv'

obj = s3.get_object(Bucket=bucket_name, Key=file_name)
data = obj['Body'].read().decode('utf-8')

data= pd.read_csv(StringIO(data))
data.head()

,agency,borough,problem,incident_zip,day_of_week,hour_of_day,problem_category,resolved_quickly
0,HPD,BRONX,HEAT/HOT WATER,10460,4,8,housing,1
1,HPD,MANHATTAN,PAINT/PLASTER,10010,4,8,housing,1
2,NYPD,QUEENS,Noise - Vehicle,11372,4,8,other,1
3,DOT,BRONX,Traffic Signal Condition,10451,4,8,traffic,1
4,NYPD,QUEENS,Illegal Parking,11101,4,8,traffic,1

In [2]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   agency            10 non-null     object
 1   borough           10 non-null     object
 2   problem           10 non-null     object
 3   incident_zip      10 non-null     int64
 4   day_of_week       10 non-null     int64
 5   hour_of_day       10 non-null     int64
 6   problem_category  10 non-null     object
 7   resolved_quickly  10 non-null     int64
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

       incident_zip  day_of_week  hour_of_day  resolved_quickly
count     10.000000         10.0         10.0         10.000000
mean   10955.600000          4.0          8.0          0.800000
std      472.935561          0.0          0.0          0.421637
min    10010.000000          4.0          8.0          0.000000
25%    10620.250000          4.0          8.0          1.000000
50%    11157.000000          4.0          8.0          1.000000
75%    11234.250000          4.0          8.0          1.000000
max    11385.000000          4.0          8.0          1.000000

In [3]:
print(data['resolved_quickly'].value_counts())
print((data['resolved_quickly'].value_counts() / len(data) * 100).round(2))

resolved_quickly
1    8
0    2
Name: count, dtype: int64
resolved_quickly
1    80.0
0    20.0
Name: count, dtype: float64